services:
  db:
    container_name: postgres
    image: 192.168.4.76:5002/postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
      POSTGRES_DB: image_db
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  pgadmin:
    image: 192.168.4.76:5002/dpage/pgadmin4:latest
    container_name: pgadmin-postgresql
    ports:
      - "8001:80"
    environment:
     PGADMIN_DEFAULT_EMAIL: postgres@email.com
     PGADMIN_DEFAULT_PASSWORD: password123
    networks:
      - db
    restart: always


  app:
    build: .
    depends_on:
      - db

networks:
  db:
#    driver: host

volumes:
  db: